import type { Schema } from './types';

const defaultSchema: Schema = {
  projects: ['Project Alpha', 'Project Beta', 'Internal Tools'],
  categories: ['bug fix', 'feature', 'meeting', 'research', 'code review', 'devops', 'documentation'],
  technologies: [
    // ── Languages ──────────────────────────────────────────────────────
    { name: 'Python', group: 'languages', subTechs: ['Flask', 'Django', 'FastAPI', 'Pandas', 'NumPy', 'SQLAlchemy', 'Celery', 'Pytest', 'Pydantic', 'BeautifulSoup', 'Asyncio', 'Typer', 'Click', 'Httpx', 'Aiohttp'] },
    { name: 'JavaScript', group: 'languages', subTechs: ['Node.js', 'Express.js', 'Hapi.js', 'Koa', 'Fastify', 'Socket.io', 'GraphQL', 'Apollo', 'Sequelize', 'Mongoose', 'PM2'] },
    { name: 'TypeScript', group: 'languages', subTechs: ['NestJS', 'Zod', 'Prisma', 'tRPC', 'tsx', 'ts-node', 'type-fest'] },
    { name: 'C#', group: 'languages', subTechs: ['.NET', 'ASP.NET Core', 'Entity Framework', 'Blazor', 'Unity', 'LINQ', 'SignalR', 'MediatR', 'AutoMapper', 'Hangfire'] },
    { name: 'Java', group: 'languages', subTechs: ['Spring Boot', 'Spring Cloud', 'Hibernate', 'Maven', 'Gradle', 'JUnit', 'Kafka Client', 'Quarkus', 'Micronaut', 'Lombok'] },
    { name: 'Go', group: 'languages', subTechs: ['Gin', 'Echo', 'Fiber', 'GORM', 'Cobra', 'Viper', 'gRPC', 'Chi', 'Air'] },
    { name: 'Rust', group: 'languages', subTechs: ['Tokio', 'Actix-Web', 'Axum', 'Serde', 'Diesel', 'SQLx', 'Tonic', 'Clap', 'Rayon'] },
    { name: 'C++', group: 'languages', subTechs: ['Qt', 'Boost', 'CMake', 'OpenCV', 'Catch2', 'gRPC', 'Abseil', 'POCO'] },
    { name: 'PHP', group: 'languages', subTechs: ['Laravel', 'Symfony', 'WordPress', 'Composer', 'Lumen', 'Slim', 'PHPUnit', 'Doctrine', 'Eloquent'] },
    { name: 'Ruby', group: 'languages', subTechs: ['Rails', 'Sinatra', 'RSpec', 'Sidekiq', 'Devise', 'ActiveRecord', 'Capistrano'] },
    { name: 'Swift', group: 'languages', subTechs: ['SwiftUI', 'UIKit', 'Combine', 'CoreData', 'Vapor', 'XCTest', 'Alamofire', 'RxSwift'] },
    { name: 'Kotlin', group: 'languages', subTechs: ['Ktor', 'Jetpack Compose', 'Coroutines', 'Room', 'Hilt', 'Flow', 'Arrow'] },
    { name: 'SQL', group: 'languages', subTechs: ['PostgreSQL', 'MySQL', 'SQLite', 'T-SQL', 'PL/pgSQL', 'Stored Procedures', 'Window Functions'] },
    { name: 'Scala', group: 'languages', subTechs: ['Akka', 'Play Framework', 'Cats', 'ZIO', 'Slick', 'sbt', 'ScalaTest'] },
    { name: 'Elixir', group: 'languages', subTechs: ['Phoenix', 'Ecto', 'GenServer', 'LiveView', 'ExUnit', 'Oban'] },
    { name: 'Haskell', group: 'languages', subTechs: ['GHC', 'Cabal', 'Stack', 'Servant', 'Yesod', 'QuickCheck'] },
    { name: 'Dart', group: 'languages', subTechs: ['Flutter', 'Riverpod', 'Bloc', 'Provider', 'Dio'] },
    { name: 'R', group: 'languages', subTechs: ['ggplot2', 'dplyr', 'tidyr', 'Shiny', 'caret', 'tidymodels', 'RMarkdown'] },
    { name: 'Shell / Bash', group: 'languages', subTechs: ['Zsh', 'Fish', 'Expect', 'awk', 'sed', 'grep', 'jq', 'yq'] },
    { name: 'Lua', group: 'languages', subTechs: ['LuaJIT', 'LÖVE', 'OpenResty'] },
    { name: 'Groovy', group: 'languages', subTechs: ['Gradle DSL', 'Spock', 'Grails'] },
    { name: 'F#', group: 'languages', subTechs: ['.NET', 'Giraffe', 'Saturn', 'FsUnit'] },
    { name: 'Solidity', group: 'languages', subTechs: ['Hardhat', 'Foundry', 'OpenZeppelin', 'Truffle', 'Ethers.js', 'Web3.js'] },
    { name: 'MATLAB', group: 'languages', subTechs: ['Simulink', 'Signal Processing Toolbox', 'Control Systems Toolbox'] },
    { name: 'Objective-C', group: 'languages', subTechs: ['CocoaTouch', 'Foundation', 'UIKit'] },
    { name: 'Perl', group: 'languages', subTechs: ['CPAN', 'Mojolicious', 'DBI'] },
    { name: 'Zig', group: 'languages', subTechs: [] },
    { name: 'Assembly', group: 'languages', subTechs: ['x86', 'ARM', 'NASM', 'GAS'] },

    // ── UI & Frontend ──────────────────────────────────────────────────
    { name: 'React', group: 'ui_frontend', subTechs: ['Redux', 'Zustand', 'Jotai', 'Recoil', 'React Query', 'SWR', 'React Hook Form', 'Formik', 'Framer Motion', 'React Router', 'React Testing Library', 'Storybook', 'React DnD', 'Virtuoso', 'React Spring'] },
    { name: 'Vue', group: 'ui_frontend', subTechs: ['Pinia', 'Vuex', 'Vue Router', 'Nuxt', 'Quasar', 'Vuelidate', 'Vue Test Utils', 'Vite', 'Composition API'] },
    { name: 'Angular', group: 'ui_frontend', subTechs: ['RxJS', 'NgRx', 'Angular Material', 'Angular CDK', 'Angular CLI', 'Nx', 'Jasmine', 'Karma', 'PrimeNG'] },
    { name: 'Svelte', group: 'ui_frontend', subTechs: ['SvelteKit', 'Svelte Stores', 'Svelte Animation', 'Vitest'] },
    { name: 'Solid.js', group: 'ui_frontend', subTechs: ['SolidStart', 'Solid Primitives'] },
    { name: 'Astro', group: 'ui_frontend', subTechs: ['Astro Islands', 'Content Collections', 'Starlight'] },
    { name: 'Next.js', group: 'ui_frontend', subTechs: ['App Router', 'Pages Router', 'Server Actions', 'Middleware', 'next-auth', 'Vercel'] },
    { name: 'Remix', group: 'ui_frontend', subTechs: ['Loaders', 'Actions', 'Nested Routes', 'defer'] },
    { name: 'HTMX', group: 'ui_frontend', subTechs: ['Hyperscript', 'Alpine.js'] },
    { name: 'Alpine.js', group: 'ui_frontend', subTechs: ['x-data', 'x-bind', 'Livewire'] },
    { name: 'Tailwind CSS', group: 'ui_frontend', subTechs: ['DaisyUI', 'Shadcn/UI', 'Headless UI', 'Radix UI', 'Flowbite', 'Tailwind UI', 'CVA'] },
    { name: 'Bootstrap', group: 'ui_frontend', subTechs: ['React Bootstrap', 'Bootstrap Icons', 'Bootswatch'] },
    { name: 'Material UI', group: 'ui_frontend', subTechs: ['MUI X', 'MUI Icons', 'Joy UI', 'Pigment CSS'] },
    { name: 'Chakra UI', group: 'ui_frontend', subTechs: ['Chakra Icons'] },
    { name: 'Ant Design', group: 'ui_frontend', subTechs: ['ProComponents', 'AntV'] },
    { name: 'Shadcn/UI', group: 'ui_frontend', subTechs: ['Radix Primitives', 'CVA', 'Tailwind Merge'] },
    { name: 'Sass / SCSS', group: 'ui_frontend', subTechs: ['Dart Sass', 'CSS Modules', 'BEM'] },
    { name: 'CSS Modules', group: 'ui_frontend', subTechs: [] },
    { name: 'Styled Components', group: 'ui_frontend', subTechs: ['ThemeProvider', 'css helper', 'createGlobalStyle'] },
    { name: 'Emotion', group: 'ui_frontend', subTechs: ['css', 'styled', 'Global', 'keyframes'] },
    { name: 'Three.js', group: 'ui_frontend', subTechs: ['React Three Fiber', 'Drei', 'Cannon', 'Rapier', 'Postprocessing'] },
    { name: 'D3.js', group: 'ui_frontend', subTechs: ['d3-scale', 'd3-axis', 'd3-force', 'Observable Plot'] },
    { name: 'Chart.js', group: 'ui_frontend', subTechs: ['react-chartjs-2', 'Chart.js 4'] },
    { name: 'Recharts', group: 'ui_frontend', subTechs: [] },
    { name: 'Vite', group: 'ui_frontend', subTechs: ['vite-plugin-pwa', 'vitest', 'Rollup', 'Rolldown'] },
    { name: 'Webpack', group: 'ui_frontend', subTechs: ['Babel', 'PostCSS', 'css-loader', 'webpack-dev-server', 'Module Federation'] },
    { name: 'Storybook', group: 'ui_frontend', subTechs: ['Chromatic', 'Addon Essentials', 'MSW addon'] },
    { name: 'Framer Motion', group: 'ui_frontend', subTechs: ['AnimatePresence', 'LayoutGroup', 'useMotionValue'] },
    { name: 'GSAP', group: 'ui_frontend', subTechs: ['ScrollTrigger', 'Draggable', 'MorphSVG'] },
    { name: 'WebAssembly', group: 'ui_frontend', subTechs: ['Emscripten', 'wasm-pack', 'WASI'] },
    { name: 'WebGL', group: 'ui_frontend', subTechs: ['GLSL', 'WebGL 2', 'TWGL'] },
    { name: 'PWA', group: 'ui_frontend', subTechs: ['Service Workers', 'Workbox', 'Web Push', 'IndexedDB'] },

    // ── Data Engineering ───────────────────────────────────────────────
    { name: 'MongoDB', group: 'data_engineering', subTechs: ['Mongoose', 'Atlas', 'Aggregation Pipeline', 'Realm', 'Change Streams'] },
    { name: 'MySQL', group: 'data_engineering', subTechs: ['InnoDB', 'MySQL Workbench', 'Replication', 'Group Replication'] },
    { name: 'PostgreSQL', group: 'data_engineering', subTechs: ['pgAdmin', 'PostGIS', 'pg_dump', 'Citus', 'TimescaleDB', 'pgvector', 'pg_bouncer'] },
    { name: 'Kafka', group: 'data_engineering', subTechs: ['Kafka Streams', 'Kafka Connect', 'Schema Registry', 'KSQL', 'Confluent', 'MSK'] },
    { name: 'Redis', group: 'data_engineering', subTechs: ['Redis Cluster', 'Redis Streams', 'RedisJSON', 'Redis Pub/Sub', 'RedisSearch', 'RedisGraph'] },
    { name: 'Kubernetes', group: 'data_engineering', subTechs: ['Helm', 'kubectl', 'Istio', 'ArgoCD', 'Kustomize', 'K9s', 'Lens', 'KEDA'] },
    { name: 'OpenShift', group: 'data_engineering', subTechs: ['OC CLI', 'Routes', 'BuildConfig', 'Operators', 'Tekton'] },
    { name: 'Docker', group: 'data_engineering', subTechs: ['Docker Compose', 'Dockerfile', 'Docker Swarm', 'Buildkit', 'Docker Scout', 'Skopeo'] },
    { name: 'Spark', group: 'data_engineering', subTechs: ['PySpark', 'Spark SQL', 'Spark Streaming', 'MLlib', 'GraphX', 'Delta Lake'] },
    { name: 'Airflow', group: 'data_engineering', subTechs: ['DAGs', 'Operators', 'Sensors', 'XComs', 'TaskFlow', 'Celery Executor'] },
    { name: 'Elasticsearch', group: 'data_engineering', subTechs: ['Kibana', 'Logstash', 'Beats', 'ELK Stack', 'APM', 'Fleet'] },
    { name: 'Snowflake', group: 'data_engineering', subTechs: ['Snowpipe', 'Streams', 'Tasks', 'dbt + Snowflake', 'Cortex AI', 'Snowpark'] },
    { name: 'dbt', group: 'data_engineering', subTechs: ['dbt Core', 'dbt Cloud', 'Jinja', 'dbt Tests', 'dbt Docs', 'dbt Metrics'] },
    { name: 'Terraform', group: 'data_engineering', subTechs: ['HCL', 'Terraform Cloud', 'Modules', 'State Management', 'Workspaces', 'Terragrunt'] },
    { name: 'BigQuery', group: 'data_engineering', subTechs: ['BigQuery ML', 'Scheduled Queries', 'Data Transfer Service', 'Omni', 'BQML'] },
    { name: 'Redshift', group: 'data_engineering', subTechs: ['Redshift Spectrum', 'Redshift Serverless', 'COPY Command', 'dbt + Redshift'] },
    { name: 'Cassandra', group: 'data_engineering', subTechs: ['CQL', 'DataStax', 'Replication Strategies', 'Astra DB'] },
    { name: 'DynamoDB', group: 'data_engineering', subTechs: ['DynamoDB Streams', 'GSI/LSI', 'DAX', 'PartiQL', 'DynamoDB Local'] },
    { name: 'Neo4j', group: 'data_engineering', subTechs: ['Cypher', 'Graph Data Science', 'APOC', 'Bloom'] },
    { name: 'ClickHouse', group: 'data_engineering', subTechs: ['MergeTree', 'Materialized Views', 'ClickHouse Cloud', 'ReplicatedMergeTree'] },
    { name: 'Flink', group: 'data_engineering', subTechs: ['Flink SQL', 'DataStream API', 'Flink CDC', 'PyFlink'] },
    { name: 'Hive', group: 'data_engineering', subTechs: ['HiveQL', 'Partitioning', 'Bucketing', 'ORC', 'Parquet'] },
    { name: 'Presto / Trino', group: 'data_engineering', subTechs: ['Connectors', 'Federation', 'Trino CLI', 'Iceberg Connector'] },
    { name: 'Delta Lake', group: 'data_engineering', subTechs: ['Time Travel', 'MERGE', 'Z-Ordering', 'DML', 'Delta Sharing'] },
    { name: 'Iceberg', group: 'data_engineering', subTechs: ['Partition Evolution', 'Schema Evolution', 'Hidden Partitioning', 'REST Catalog'] },
    { name: 'Databricks', group: 'data_engineering', subTechs: ['Notebooks', 'Unity Catalog', 'Workflows', 'MLflow', 'Delta Live Tables', 'Lakehouse'] },
    { name: 'Grafana', group: 'data_engineering', subTechs: ['Dashboards', 'Alerting', 'Loki', 'Tempo', 'Mimir', 'OnCall'] },
    { name: 'Prometheus', group: 'data_engineering', subTechs: ['PromQL', 'Alertmanager', 'Exporters', 'Thanos', 'VictoriaMetrics'] },
    { name: 'RabbitMQ', group: 'data_engineering', subTechs: ['Exchanges', 'Queues', 'Bindings', 'Management UI', 'Shovel', 'Federation'] },
    { name: 'NATS', group: 'data_engineering', subTechs: ['JetStream', 'NATS Streaming', 'Subject-Based Messaging', 'Leaf Nodes'] },
    { name: 'SQLite', group: 'data_engineering', subTechs: ['WAL Mode', 'FTS5', 'SQLite Extensions', 'Turso', 'Cloudflare D1'] },
    { name: 'Microsoft SQL Server', group: 'data_engineering', subTechs: ['T-SQL', 'SSMS', 'SSRS', 'SSIS', 'Always On', 'Replication'] },
    { name: 'Oracle DB', group: 'data_engineering', subTechs: ['PL/SQL', 'RAC', 'Data Guard', 'APEX', 'Autonomous DB'] },
    { name: 'CockroachDB', group: 'data_engineering', subTechs: ['Distributed SQL', 'CockroachCloud', 'CRDB Multi-Region'] },
    { name: 'Supabase', group: 'data_engineering', subTechs: ['Supabase Auth', 'Supabase Storage', 'Realtime', 'Edge Functions', 'pgvector'] },
    { name: 'PlanetScale', group: 'data_engineering', subTechs: ['Vitess', 'Database Branching', 'Non-blocking Migrations'] },
    { name: 'Neon', group: 'data_engineering', subTechs: ['Serverless Postgres', 'Branching', 'Autoscaling'] },

    // ── Cloud & Platforms ──────────────────────────────────────────────
    { name: 'AWS', group: 'cloud_and_platforms', subTechs: ['EC2', 'S3', 'Lambda', 'RDS', 'ECS', 'EKS', 'SQS', 'SNS', 'CloudFormation', 'IAM', 'CloudWatch', 'API Gateway', 'Step Functions', 'Glue', 'Athena', 'Kinesis', 'DMS', 'Amplify', 'App Runner', 'Bedrock', 'CDK'] },
    { name: 'Azure', group: 'cloud_and_platforms', subTechs: ['Azure Functions', 'AKS', 'Blob Storage', 'Azure SQL', 'CosmosDB', 'Azure DevOps', 'Event Hub', 'Data Factory', 'Service Bus', 'API Management', 'Azure AI', 'Bicep', 'Azure Container Apps'] },
    { name: 'GCP', group: 'cloud_and_platforms', subTechs: ['Cloud Functions', 'GKE', 'Cloud Storage', 'Cloud SQL', 'Pub/Sub', 'Dataflow', 'Cloud Run', 'BigTable', 'Looker', 'Vertex AI', 'Firebase', 'Cloud Armor'] },
    { name: 'Git', group: 'cloud_and_platforms', subTechs: ['GitHub', 'GitLab', 'Bitbucket', 'Git Flow', 'GitHub Actions', 'GitLab CI', 'Gitea', 'Trunk-Based Development'] },
    { name: 'Jenkins', group: 'cloud_and_platforms', subTechs: ['Jenkinsfile', 'Pipeline', 'Blue Ocean', 'Shared Libraries', 'Jenkins X'] },
    { name: 'Vercel', group: 'cloud_and_platforms', subTechs: ['Edge Functions', 'Analytics', 'Vercel KV', 'Vercel Postgres', 'AI SDK'] },
    { name: 'Netlify', group: 'cloud_and_platforms', subTechs: ['Edge Functions', 'Netlify CMS', 'Identity', 'Forms', 'Build Plugins'] },
    { name: 'Cloudflare', group: 'cloud_and_platforms', subTechs: ['Workers', 'Pages', 'R2', 'D1', 'KV', 'Durable Objects', 'WAF', 'CDN', 'Tunnel'] },
    { name: 'DigitalOcean', group: 'cloud_and_platforms', subTechs: ['Droplets', 'App Platform', 'Spaces', 'Managed Kubernetes', 'Managed Databases'] },
    { name: 'Heroku', group: 'cloud_and_platforms', subTechs: ['Dynos', 'Add-ons', 'Pipelines', 'Heroku Postgres'] },
    { name: 'Railway', group: 'cloud_and_platforms', subTechs: ['Services', 'Templates', 'Volumes', 'Nixpacks'] },
    { name: 'Fly.io', group: 'cloud_and_platforms', subTechs: ['Machines', 'Volumes', 'fly launch', 'Tigris Storage'] },

    // ── DevOps & CI/CD ─────────────────────────────────────────────────
    { name: 'GitHub Actions', group: 'devops', subTechs: ['Workflows', 'Actions Marketplace', 'Self-Hosted Runners', 'Matrix Strategy', 'Reusable Workflows', 'OIDC'] },
    { name: 'GitLab CI', group: 'devops', subTechs: ['Pipelines', 'Runners', 'GitLab Registry', 'Review Apps', 'DAST', 'SAST'] },
    { name: 'CircleCI', group: 'devops', subTechs: ['Orbs', 'Pipelines', 'Insights', 'Self-Hosted Runners'] },
    { name: 'ArgoCD', group: 'devops', subTechs: ['GitOps', 'Application Sets', 'Sync Waves', 'Argo Rollouts', 'Argo Workflows', 'Argo Events'] },
    { name: 'Flux', group: 'devops', subTechs: ['FluxCD v2', 'Kustomize Controller', 'Helm Controller', 'Image Automation'] },
    { name: 'Ansible', group: 'devops', subTechs: ['Playbooks', 'Roles', 'Galaxy', 'AWX', 'Tower', 'Collections', 'Molecule'] },
    { name: 'Terraform', group: 'devops', subTechs: ['HCL', 'Terraform Cloud', 'Modules', 'Workspaces', 'Terragrunt', 'Atlantis', 'Checkov'] },
    { name: 'Pulumi', group: 'devops', subTechs: ['Python SDK', 'TypeScript SDK', 'ESC', 'Automation API'] },
    { name: 'Helm', group: 'devops', subTechs: ['Charts', 'Repositories', 'Hooks', 'Values', 'Helmfile'] },
    { name: 'Nginx', group: 'devops', subTechs: ['Reverse Proxy', 'Load Balancing', 'SSL Termination', 'Nginx Plus', 'NGINX Unit'] },
    { name: 'Traefik', group: 'devops', subTechs: ['Middleware', 'Let\'s Encrypt', 'Dashboard', 'Kubernetes Ingress'] },
    { name: 'Vault', group: 'devops', subTechs: ['Secrets Engine', 'Auth Methods', 'PKI', 'Dynamic Secrets', 'Vault Agent'] },
    { name: 'Consul', group: 'devops', subTechs: ['Service Mesh', 'KV Store', 'Health Checks', 'Connect'] },
    { name: 'OpenTelemetry', group: 'devops', subTechs: ['Traces', 'Metrics', 'Logs', 'Collector', 'OTLP', 'Jaeger', 'Tempo'] },
    { name: 'Datadog', group: 'devops', subTechs: ['APM', 'Logs', 'Metrics', 'RUM', 'Synthetics', 'Security Monitoring'] },
    { name: 'Sentry', group: 'devops', subTechs: ['Error Tracking', 'Performance', 'Session Replay', 'Crons'] },
    { name: 'New Relic', group: 'devops', subTechs: ['APM', 'Infrastructure', 'Browser', 'Dashboards'] },
    { name: 'Trivy', group: 'devops', subTechs: ['Container Scanning', 'IaC Scanning', 'SBOM', 'Filesystem Scanning'] },
    { name: 'SonarQube', group: 'devops', subTechs: ['Code Quality', 'SAST', 'SonarCloud', 'Quality Gates'] },
    { name: 'TeamCity', group: 'devops', subTechs: ['Build Chains', 'Kotlin DSL', 'Cloud Agents'] },
    { name: 'Buildkite', group: 'devops', subTechs: ['Pipelines', 'Self-Hosted Agents', 'Test Analytics'] },

    // ── Testing & QA ───────────────────────────────────────────────────
    { name: 'Jest', group: 'testing', subTechs: ['jest.mock', 'jest-dom', 'jest-circus', 'ts-jest', 'babel-jest', 'jest-extended'] },
    { name: 'Vitest', group: 'testing', subTechs: ['vi.mock', 'browser mode', 'coverage', 'snapshot testing'] },
    { name: 'Cypress', group: 'testing', subTechs: ['E2E', 'Component Testing', 'Cypress Cloud', 'cy.intercept'] },
    { name: 'Playwright', group: 'testing', subTechs: ['API Testing', 'Visual Comparison', 'Codegen', 'Traces', 'Sharding'] },
    { name: 'Selenium', group: 'testing', subTechs: ['WebDriver', 'Grid', 'IDE', 'Page Object Model'] },
    { name: 'Testing Library', group: 'testing', subTechs: ['React Testing Library', 'user-event', 'jest-dom', 'Vue Testing Library'] },
    { name: 'PyTest', group: 'testing', subTechs: ['Fixtures', 'Parametrize', 'pytest-cov', 'pytest-mock', 'pytest-asyncio', 'Factory Boy'] },
    { name: 'JUnit', group: 'testing', subTechs: ['JUnit 5', 'Mockito', 'AssertJ', 'Parameterized Tests'] },
    { name: 'RSpec', group: 'testing', subTechs: ['FactoryBot', 'Capybara', 'VCR', 'Shoulda Matchers'] },
    { name: 'k6', group: 'testing', subTechs: ['Scenarios', 'Thresholds', 'k6 Cloud', 'xk6 Extensions'] },
    { name: 'Gatling', group: 'testing', subTechs: ['Simulations', 'Feeders', 'Assertions', 'Scala DSL'] },
    { name: 'Postman', group: 'testing', subTechs: ['Collections', 'Environments', 'Newman', 'Monitors', 'Mock Servers'] },
    { name: 'Pact', group: 'testing', subTechs: ['Consumer-Driven Contracts', 'Pact Broker', 'Bidirectional Contracts'] },
    { name: 'MSW', group: 'testing', subTechs: ['Service Worker', 'Node Integration', 'REST Handlers', 'GraphQL Handlers'] },
    { name: 'Stryker', group: 'testing', subTechs: ['Mutation Testing', 'Stryker Dashboard'] },
    { name: 'Mocha', group: 'testing', subTechs: ['Chai', 'Sinon', 'Nock', 'Supertest'] },
    { name: 'TestCafe', group: 'testing', subTechs: ['Cross-Browser', 'Selectors', 'Smart Assertions'] },
    { name: 'Artillery', group: 'testing', subTechs: ['Load Testing', 'Cloud', 'Plugins'] },

    // ── AI & Machine Learning ─────────────────────────────────────────
    { name: 'TensorFlow', group: 'ai_ml', subTechs: ['Keras', 'TF Serving', 'TF Lite', 'TF.js', 'TF Extended', 'TensorBoard'] },
    { name: 'PyTorch', group: 'ai_ml', subTechs: ['TorchVision', 'TorchText', 'TorchAudio', 'PyTorch Lightning', 'FSDP', 'TorchScript', 'ONNX'] },
    { name: 'Hugging Face', group: 'ai_ml', subTechs: ['Transformers', 'Datasets', 'PEFT', 'Accelerate', 'Diffusers', 'TRL', 'Hub', 'Spaces'] },
    { name: 'LangChain', group: 'ai_ml', subTechs: ['Chains', 'Agents', 'RAG', 'LangGraph', 'LangSmith', 'LCEL', 'Vector Stores'] },
    { name: 'LlamaIndex', group: 'ai_ml', subTechs: ['Index Types', 'Query Engine', 'Data Connectors', 'LlamaParse'] },
    { name: 'OpenAI API', group: 'ai_ml', subTechs: ['GPT-4o', 'Chat Completions', 'Embeddings', 'DALL-E', 'Whisper', 'Function Calling', 'Assistants API', 'Fine-tuning'] },
    { name: 'Anthropic API', group: 'ai_ml', subTechs: ['Claude 4', 'Messages API', 'Tool Use', 'Vision', 'Streaming', 'Prompt Caching', 'Extended Thinking'] },
    { name: 'Ollama', group: 'ai_ml', subTechs: ['Local Models', 'Modelfile', 'REST API', 'llama.cpp'] },
    { name: 'scikit-learn', group: 'ai_ml', subTechs: ['Pipelines', 'GridSearchCV', 'Feature Selection', 'Preprocessing', 'Ensemble Methods'] },
    { name: 'XGBoost', group: 'ai_ml', subTechs: ['DMatrix', 'DART', 'GPU Support', 'Feature Importance'] },
    { name: 'LightGBM', group: 'ai_ml', subTechs: ['GBDT', 'DART Mode', 'GOSS', 'Categorical Features'] },
    { name: 'MLflow', group: 'ai_ml', subTechs: ['Tracking', 'Projects', 'Models', 'Registry', 'Recipes'] },
    { name: 'Weights & Biases', group: 'ai_ml', subTechs: ['Runs', 'Sweeps', 'Artifacts', 'Reports', 'Tables', 'Prompts'] },
    { name: 'Ray', group: 'ai_ml', subTechs: ['Ray Serve', 'Ray Train', 'Ray Tune', 'Ray Data', 'Anyscale'] },
    { name: 'Kubeflow', group: 'ai_ml', subTechs: ['Pipelines', 'Notebooks', 'Katib', 'KServe', 'Training Operator'] },
    { name: 'Streamlit', group: 'ai_ml', subTechs: ['st.cache', 'Session State', 'Forms', 'Streamlit Cloud', 'Components'] },
    { name: 'Gradio', group: 'ai_ml', subTechs: ['Interface', 'Blocks', 'Spaces', 'gr.Request'] },
    { name: 'OpenCV', group: 'ai_ml', subTechs: ['Image Processing', 'Object Detection', 'Video Capture', 'DNN Module'] },
    { name: 'spaCy', group: 'ai_ml', subTechs: ['NER', 'POS Tagging', 'Dependency Parsing', 'Custom Pipelines', 'Prodigy'] },
    { name: 'Stable Diffusion', group: 'ai_ml', subTechs: ['LoRA', 'ControlNet', 'AUTOMATIC1111', 'ComfyUI', 'Diffusers'] },
    { name: 'Pinecone', group: 'ai_ml', subTechs: ['Vector Search', 'Namespaces', 'Hybrid Search', 'Serverless'] },
    { name: 'Weaviate', group: 'ai_ml', subTechs: ['Vector DB', 'Hybrid Search', 'Generative Search', 'HNSW'] },
    { name: 'Chroma', group: 'ai_ml', subTechs: ['Persistent Client', 'Embeddings', 'Collections'] },
    { name: 'Vertex AI', group: 'ai_ml', subTechs: ['Gemini API', 'AutoML', 'Feature Store', 'Model Garden', 'Pipelines'] },

    // ── Mobile ─────────────────────────────────────────────────────────
    { name: 'React Native', group: 'mobile', subTechs: ['Expo', 'React Navigation', 'Expo Router', 'Reanimated', 'Gesture Handler', 'MMKV', 'Zustand', 'NativeWind'] },
    { name: 'Flutter', group: 'mobile', subTechs: ['Dart', 'BLoC', 'Riverpod', 'Provider', 'Dio', 'GetX', 'go_router', 'Flavor'] },
    { name: 'Expo', group: 'mobile', subTechs: ['EAS Build', 'EAS Update', 'Expo Go', 'Modules API', 'Push Notifications'] },
    { name: 'Swift / SwiftUI', group: 'mobile', subTechs: ['UIKit', 'Combine', 'CoreData', 'CloudKit', 'HealthKit', 'ARKit', 'AVFoundation'] },
    { name: 'Kotlin / Jetpack', group: 'mobile', subTechs: ['Jetpack Compose', 'Room', 'Hilt', 'ViewModel', 'WorkManager', 'DataStore', 'Coroutines', 'Flow'] },
    { name: 'Ionic', group: 'mobile', subTechs: ['Capacitor', 'Cordova', 'Stencil', 'Ionic Angular', 'Ionic React'] },
    { name: '.NET MAUI', group: 'mobile', subTechs: ['Blazor Hybrid', 'Shell', 'CommunityToolkit', 'MVVM'] },
    { name: 'Kotlin Multiplatform', group: 'mobile', subTechs: ['Compose Multiplatform', 'Ktor Client', 'SQLDelight', 'Korlibs'] },
    { name: 'Android SDK', group: 'mobile', subTechs: ['Activity', 'Fragment', 'RecyclerView', 'Navigation Component', 'Gradle', 'ProGuard'] },

    // ── Security ───────────────────────────────────────────────────────
    { name: 'OWASP', group: 'security', subTechs: ['Top 10', 'ASVS', 'ZAP', 'Dependency-Check', 'Juice Shop'] },
    { name: 'JWT / OAuth', group: 'security', subTechs: ['JWT', 'OAuth 2.0', 'OpenID Connect', 'PKCE', 'Refresh Tokens', 'Keycloak', 'Auth0', 'Okta'] },
    { name: 'Penetration Testing', group: 'security', subTechs: ['Burp Suite', 'Metasploit', 'Nmap', 'Nikto', 'SQLMap', 'Hydra', 'ffuf', 'gobuster'] },
    { name: 'Cryptography', group: 'security', subTechs: ['AES', 'RSA', 'ECDSA', 'TLS 1.3', 'bcrypt', 'Argon2', 'Let\'s Encrypt', 'HSM'] },
    { name: 'Snyk', group: 'security', subTechs: ['Snyk Code', 'Snyk Open Source', 'Snyk Container', 'Snyk IaC'] },
    { name: 'HashiCorp Vault', group: 'security', subTechs: ['Secrets Management', 'PKI', 'Dynamic Secrets', 'Vault Agent', 'Transit Engine'] },
    { name: 'CrowdStrike', group: 'security', subTechs: ['Falcon EDR', 'Threat Intelligence', 'Identity Protection'] },
    { name: 'Wireshark', group: 'security', subTechs: ['Packet Capture', 'Display Filters', 'tshark', 'Follow Stream'] },
    { name: 'SIEM', group: 'security', subTechs: ['Splunk', 'Elastic SIEM', 'Wazuh', 'IBM QRadar', 'Microsoft Sentinel'] },
    { name: 'WAF', group: 'security', subTechs: ['Cloudflare WAF', 'AWS WAF', 'ModSecurity', 'F5 ASM'] },
  ],
};

export const GROUP_LABELS: Record<string, string> = {
  languages: 'Languages',
  ui_frontend: 'UI & Frontend',
  data_engineering: 'Data Engineering',
  cloud_and_platforms: 'Cloud & Platforms',
  devops: 'DevOps & CI/CD',
  testing: 'Testing & QA',
  ai_ml: 'AI & Machine Learning',
  mobile: 'Mobile',
  security: 'Security',
};

export const GROUP_ORDER = [
  'languages',
  'ui_frontend',
  'data_engineering',
  'cloud_and_platforms',
  'devops',
  'testing',
  'ai_ml',
  'mobile',
  'security',
];

export default defaultSchema;
